"""
XEGPU runner example accepting GPU-level kernel.
Only for matrix multiplications.
"""

import argparse
import json
import sys
from dataclasses import dataclass
from typing import Optional, ClassVar
from functools import cached_property

import numpy as np
from mlir import ir

from lighthouse import dialects as lh_dialects
from lighthouse.execution.runner import Runner
from lighthouse.pipeline.driver import TransformDriver
from lighthouse.execution import (
    MemoryManager,
    GPUMemoryManager,
)
from lighthouse.schedule.xegpu import mlp_schedule, xegpu_to_binary
from lighthouse.utils.numpy import mlir_to_numpy_dtype
from lighthouse.ingress.mlir_gen import get_mlir_elem_type
from lighthouse.schedule.xegpu import xegpu_parameter_selector


def matmul_complexity(
    M: int,
    N: int,
    K: int,
    bias: bool,
    relu: bool,
    accumulate_c: bool,
    nbytes_ab: int,
    nbytes_c: int,
):
    """Complexity of matmul operation with optional post-ops"""
    flop_count = 2 * M * N * K
    memory_reads = (M * K + K * N) * nbytes_ab  # read A and B
    memory_writes = M * N * nbytes_c  # write C
    # Below we assume the post-ops are tiled-and-fused and do not cause
    # reads/writes to global memory.
    if bias:
        flop_count += M * N
        memory_reads += N * nbytes_c  # read bias vector
    if relu:
        flop_count += M * N
    if accumulate_c:
        memory_reads += M * N * nbytes_c  # read C for accumulation
    return flop_count, memory_reads, memory_writes


@dataclass
class XeGPUMatMul:
    """
    Matrix multiplication kernel on XeGPU.

    Computes C = A * B for input matrices A (M x K) and B (K x N).
    """

    payload_function_name: ClassVar[str] = "payload"
    memory_manager_class: ClassVar[type[MemoryManager]] = GPUMemoryManager

    M: int = 1024
    N: int = 1024
    K: int = 1024
    ab_type: ir.Type | str | None = None
    c_type: ir.Type | str | None = None
    mlir_file: Optional[str] = None
    gpu_func_name: Optional[str] = None
    init_int: bool = False

    def __post_init__(self):
        if isinstance(self.ab_type, str):
            self.ab_type = get_mlir_elem_type(self.ab_type)
        if isinstance(self.c_type, str):
            self.c_type = get_mlir_elem_type(self.c_type)
        if self.ab_type is None:
            self.ab_type = ir.F16Type.get()
        if self.c_type is None:
            self.c_type = ir.F32Type.get()
        assert isinstance(self.ab_type, ir.F16Type), (
            "Only f16 type is supported for A and B"
        )
        assert isinstance(self.c_type, ir.F32Type), "Only f32 type is supported for C"
        self.ab_dtype = mlir_to_numpy_dtype(self.ab_type)
        self.c_dtype = mlir_to_numpy_dtype(self.c_type)
        self.a_shape = (self.M, self.K)
        self.b_shape = (self.K, self.N)
        self.c_shape = (self.M, self.N)

    @cached_property
    def _initial_host_arrays(self) -> list[np.ndarray]:
        """Generate initial values on host with numpy."""

        # use integer values to avoid f16/f32 floating point discrepancies
        def gen_random(shape, dtype):
            if not self.init_int:
                # generate values in range [-0.5, 0.5]
                return (np.random.rand(*shape) - 0.5).astype(dtype)
            # generate values in range [-3, 3]
            a = np.random.randint(-3, 4, shape)
            return a.astype(dtype)

        np.random.seed(2)
        A = gen_random(self.a_shape, self.ab_dtype)
        B = gen_random(self.b_shape, self.ab_dtype)
        C = gen_random(self.c_shape, self.c_dtype)
        return C, A, B

    def get_complexity(self) -> tuple[int, int, int]:
        nbytes_ab = np.dtype(self.ab_dtype).itemsize
        nbytes_c = np.dtype(self.c_dtype).itemsize
        return matmul_complexity(
            self.M,
            self.N,
            self.K,
            False,
            False,
            False,
            nbytes_ab,
            nbytes_c,
        )

    def payload_module(self) -> ir.Module:
        if self.mlir_file is None or self.mlir_file == "-":
            mlir_text = sys.stdin.read()
        else:
            with open(self.mlir_file, "r") as f:
                mlir_text = f.read()

        mod = ir.Module.parse(mlir_text)

        # If gpu_func_name is set, remove any existing host launcher function
        # (it will be regenerated by add_host_launcher).
        if self.gpu_func_name:
            for op in list(mod.body.operations):
                if op.OPERATION_NAME == "func.func":
                    if op.attributes["sym_name"].value == self.payload_function_name:
                        op.erase()

        ranks_and_types = [(2, self.ab_type), (2, self.c_type)]
        self.memory_manager_class.emit_memory_management_funcs(
            mod, ranks_and_types=ranks_and_types
        )
        return mod

    def schedule_modules(
        self, stop_at_stage: Optional[str] = None, parameters: Optional[dict] = None
    ) -> list[ir.Module]:
        assert parameters is not None, "Schedule parameters must be provided"
        schedules = []
        if self.gpu_func_name is not None:
            name = self.gpu_func_name if self.gpu_func_name else None
            block_size = None
            if (
                parameters.get("wg_m")
                and parameters.get("sg_m")
                and parameters.get("wg_n")
                and parameters.get("sg_n")
            ):
                nb_threads = (
                    (parameters["wg_m"] // parameters["sg_m"])
                    * (parameters["wg_n"] // parameters["sg_n"])
                    * 16
                )
                block_size = nb_threads
            schedules.append(
                Runner.get_host_launcher_schedule(
                    name, self.payload_function_name, block_size=block_size
                )
            )
        schedules.append(
            Runner.get_bench_wrapper_schedule(self.payload_function_name),
        )

        schedules.append(
            mlp_schedule(
                start_from_gpu=True,
                stop_at_stage=stop_at_stage,
                params=[parameters],
            )
        )

        if stop_at_stage and stop_at_stage != "final":
            return schedules

        schedules.append(xegpu_to_binary())

        return schedules

    def shared_libs(self) -> list[str]:
        return ["libmlir_levelzero_runtime.so"]


def check_results(
    mmul: XeGPUMatMul, payload: ir.Module, buffers: list[np.ndarray], verbose: int = 0
) -> bool:
    """
    Check correctness of the result.
    """
    # Compute reference solution on host.
    host_inputs = mmul._initial_host_arrays
    C, A, B = host_inputs[:3]

    # use float32 data type for efficiency
    f32 = np.float32
    D_ref = A.astype(f32) @ B.astype(f32)
    # D_ref += C.astype(f32)

    D_host = buffers[0].astype(np.float32)
    if verbose > 1:
        print("Reference solution:")
        print(D_ref)
        print("Computed solution:")
        print(D_host)
    success = np.allclose(D_host, D_ref)

    if verbose:
        if success:
            print("PASSED")
        else:
            print("FAILED Result mismatch!")

    return success


def cli_parser(description):
    """CLI argument parser for args shared with autotuner."""
    parser = argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--all-knobs", action="store_true", help="Use knobs for all schedule parameters"
    )
    parser.add_argument(
        "--sizes",
        type=int,
        nargs=3,
        default=[4096, 4096, 4096],
        help="M,N,K matrix sizes (A=MxK, B=KxN, C=MxN).",
    )
    return parser


def parse_cli_args(description):
    parser = cli_parser(description=description)
    parser.add_argument(
        "--wg-tile",
        type=int,
        nargs=2,
        help="Workgroup tile size M,N.",
    )
    parser.add_argument(
        "--sg-tile",
        type=int,
        nargs=2,
        help="Subgroup tile size M,N.",
    )
    parser.add_argument(
        "--k-tile",
        type=int,
        help="Inner reduction dimension tile size K.",
    )
    parser.add_argument(
        "--load-tile-a",
        type=int,
        nargs=2,
        help="Tile size for loading A matrix for DPAS op.",
    )
    parser.add_argument(
        "--load-tile-b",
        type=int,
        nargs=2,
        help="Tile size for loading B matrix for DPAS op.",
    )
    parser.add_argument(
        "--prefetch-tile-a",
        type=int,
        nargs=2,
        help="Tile size for cooperative prefetching of subgroup A matrix",
    )
    parser.add_argument(
        "--prefetch-tile-b",
        type=int,
        nargs=2,
        help="Tile size for cooperative prefetching of subgroup B matrix",
    )
    parser.add_argument(
        "--prefetch-a-nb",
        type=int,
        help="Number of initial prefetches for A matrix.",
    )
    parser.add_argument(
        "--prefetch-b-nb",
        type=int,
        help="Number of initial prefetches for B matrix.",
    )
    parser.add_argument(
        "--check-result",
        action="store_true",
        help="Check the result of the matrix multiplication.",
    )
    parser.add_argument(
        "--init-int",
        action="store_true",
        help="Initialize data with integers in range [-3, 3] instead of floats.",
    )
    parser.add_argument(
        "--nruns",
        type=int,
        default=1000,
        help="Number of runs to average the execution time.",
    )
    parser.add_argument(
        "--nwarmup",
        type=int,
        default=20,
        help="Number of warm-up iterations before benchmarking.",
    )
    parser.add_argument(
        "--dump-kernel",
        type=str,
        choices=[
            "initial",
            "tiled",
            "vectorized",
            "bufferized",
            "xegpu-initial",
            "xegpu-wg",
            "final",
        ],
        help="Dump kernel IR at different stages of lowering and exit without "
        "executing the kernel.",
    )
    parser.add_argument(
        "--dump-schedule",
        action="store_true",
        help="Dump transform schedule.",
    )
    parser.add_argument(
        "--json",
        help="Read problem sizes and tile parameters from a JSON file.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="count",
        default=0,
        help="Increase output verbosity (e.g. print reference and computed solutions).",
    )
    parser.add_argument(
        "input",
        nargs="?",
        default=None,
        help="MLIR input file. If not provided or '-', read from stdin.",
    )
    args = parser.parse_args()

    if args.check_result and not args.init_int:
        parser.error(
            "--check-result requires --init-int (float verification is not supported)."
        )

    return args


if __name__ == "__main__":
    description = """XeGPU matrix multiplication example with tunable parameters.

If run without arguments, executes a M=N=K=4096 matrix-multiply-accumulate
kernel on default tile sizes. The problem size and tile
sizes can be overridden by providing a JSON file or using the CLI arguments.
CLI arguments take precedence over everything else.
"""
    args = parse_cli_args(description=description)

    # Problem size
    m, n, k = args.sizes if args.sizes else (4096, 4096, 4096)
    # Get default parameters from the database
    try:
        params = xegpu_parameter_selector.get_matmul_parameters(m, n, k)
    except ValueError:
        # Initialize with a stub and assume the rest will be populated
        params = {
            "m": m,
            "n": n,
            "k": k,
            "wg_m": None,
            "wg_n": None,
            "sg_m": None,
            "sg_n": None,
            "k_tile": None,
            "load_a_m": None,
            "load_a_k": None,
            "load_b_k": None,
            "load_b_n": None,
            "prefetch_a_m": None,
            "prefetch_a_k": None,
            "prefetch_b_k": None,
            "prefetch_b_n": None,
            "prefetch_a_nb": None,
            "prefetch_b_nb": None,
        }
    if args.json:
        # Override parameters with values from JSON file if provided
        with open(args.json, "r") as f:
            json_params = json.load(f)
        params.update(json_params)

    # Override parameters with CLI args if provided
    if args.wg_tile:
        params["wg_m"], params["wg_n"] = args.wg_tile
    if args.sg_tile:
        params["sg_m"], params["sg_n"] = args.sg_tile
    if args.k_tile:
        params["k_tile"] = args.k_tile
    if args.load_tile_a:
        params["load_a_m"], params["load_a_k"] = args.load_tile_a
    if args.load_tile_b:
        params["load_b_k"], params["load_b_n"] = args.load_tile_b
    if args.prefetch_tile_a:
        params["prefetch_a_m"], params["prefetch_a_k"] = args.prefetch_tile_a
    if args.prefetch_tile_b:
        params["prefetch_b_k"], params["prefetch_b_n"] = args.prefetch_tile_b
    if args.prefetch_a_nb is not None:
        params["prefetch_a_nb"] = args.prefetch_a_nb
    if args.prefetch_b_nb is not None:
        params["prefetch_b_nb"] = args.prefetch_b_nb

    for k, v in params.items():
        if v is None:
            raise ValueError(
                f"Parameter {k} is not set. Please provide it via CLI or JSON file."
            )

    with ir.Context(), ir.Location.unknown():
        lh_dialects.register_and_load()

        wload = XeGPUMatMul(
            M=params["m"],
            N=params["n"],
            K=params["k"],
            mlir_file=args.input,
            gpu_func_name="",
            init_int=args.init_int,
        )

        if args.dump_kernel or args.dump_schedule:
            if args.dump_kernel:
                pipeline = TransformDriver(
                    wload.schedule_modules(
                        stop_at_stage=args.dump_kernel, parameters=params
                    )
                )
                payload = pipeline.apply(wload.payload_module())
                print(payload)
            if args.dump_schedule:
                for schedule_module in wload.schedule_modules(parameters=params):
                    print(schedule_module)
        else:
            pipeline = TransformDriver(wload.schedule_modules(parameters=params))
            payload = pipeline.apply(wload.payload_module())
            runner = Runner(
                payload,
                mem_manager_cls=wload.memory_manager_class,
                shared_libs=wload.shared_libs(),
            )
            if args.check_result:
                # Setup callback function to copy result from device to host.
                D_host_copy = np.zeros(wload.c_shape, dtype=wload.c_dtype)
                argument_access_callback = Runner.get_gpu_argument_access_callback(
                    D_host_copy, arg_index=0
                )

                runner.execute(
                    host_input_buffers=wload._initial_host_arrays,
                    payload_function_name=wload.payload_function_name,
                    argument_access_callback=argument_access_callback,
                )
                success = check_results(wload, payload, [D_host_copy], args.verbose)
                if not success:
                    raise ValueError("Result mismatch!")

            times = runner.benchmark(
                host_input_buffers=wload._initial_host_arrays,
                nruns=args.nruns,
                nwarmup=args.nwarmup,
            )
            times *= 1e6  # convert to microseconds
            elapsed_mean = np.mean(times)
            elapsed_max = np.max(times)
            elapsed_min = np.min(times)
            flop_count = wload.get_complexity()[0]
            gflops_mean = flop_count / (elapsed_mean * 1e-6) / 1e9
            gflops_max = flop_count / (elapsed_min * 1e-6) / 1e9
            gflops_min = flop_count / (elapsed_max * 1e-6) / 1e9

            def list2str(a):
                return ",".join(map(str, a))

            ab_type = str(wload.ab_type)
            c_type = str(wload.c_type)
            print(
                f"sizes={list2str([params['m'], params['n'], params['k']])} "
                f"dt={ab_type},{c_type} "
                f"wg-tile={list2str([params['wg_m'], params['wg_n']])} "
                f"sg-tile={list2str([params['sg_m'], params['sg_n']])} "
                f"k-tile={params['k_tile']} "
                f"load-a-tile={list2str([params['load_a_m'], params['load_a_k']])} "
                f"load-b-tile={list2str([params['load_b_k'], params['load_b_n']])} "
                f"pf-a-tile={list2str([params['prefetch_a_m'], params['prefetch_a_k']])} "
                f"pf-b-tile={list2str([params['prefetch_b_k'], params['prefetch_b_n']])} "
                f"time_mean(us): {elapsed_mean:.2f} "
                f"time_max(us): {elapsed_max:.2f} "
                f"GFLOPS_mean: {gflops_mean:.2f} "
                f"GFLOPS_max: {gflops_max:.2f}"
            )
